namespace ViewsLife.Api.Infrastructure.Options;

/// Represents JWT configuration values used for issuing and validating tokens.
/// These values are loaded from configuration so they can vary by environment
/// without changing application code.

public sealed class JwtOptions
{
    /// The configuration section name used when binding these options.
    public const string SectionName = "Jwt";
    
    /// The logical issuer for tokens generated by the application.
    public string Issuer { get; set; } = string.Empty;

    /// The intended audience for tokens generated by the application.
    public string Audience { get; set; } = string.Empty;

    /// The secret key used for signing tokens.
    /// This should be long, random, and stored securely per environment.
    public string Secret { get; set; } = string.Empty;
}